name: Test

on:
    push:
        branches:
            main

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - run: docker build --platform linux/amd64 -t patinocode/aws-ddns:latest .
            - run: docker push patinocode/aws-ddns:latest